name: Run test and lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Set up Bundler with GitHub Packages
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          bundle config set --local BUNDLE_RUBYGEMS__PKG__GITHUB__COM $BUNDLE_RUBYGEMS__PKG__GITHUB__COM
          bundle install

      - name: Run rspec
        run: bundle exec rake spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Set up Bundler with GitHub Packages
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          bundle config set --local BUNDLE_RUBYGEMS__PKG__GITHUB__COM $BUNDLE_RUBYGEMS__PKG__GITHUB__COM
          bundle install

      - name: Run RuboCop
        run: bundle exec rake rubocop
